The-Samyar/Receiptly

Receiptly/api/serializers.py
Receiptly/api/urls.py
Receiptly/api/views.py

- Modified the serializers to output JSON with a better format
- Created api URL endpoints

API endpoints and JSON

---

Receiptly/receiptly-front/.gitignore
Receiptly/receiptly-front/README.md
Receiptly/receiptly-front/package-lock.json
Receiptly/receiptly-front/package.json
Receiptly/receiptly-front/public/index.html
Receiptly/receiptly-front/public/manifest.json
Receiptly/receiptly-front/public/robots.txt
Receiptly/receiptly-front/src/App.css
Receiptly/receiptly-front/src/App.js
Receiptly/receiptly-front/src/App.test.js
Receiptly/receiptly-front/src/index.css
Receiptly/receiptly-front/src/index.js

- Initialize client-side directory
- Initialize React along with its dependencies

Initialize client-side directory

---

Receiptly/receiptly-front/src/App.css
Receiptly/receiptly-front/src/Components/Navbar/Navbar.css
Receiptly/receiptly-front/src/Components/Navbar/Navbar.jsx
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.css
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.jsx
Receiptly/receiptly-front/src/Pages/Home.jsx

- Complete ReceiptCard component implementation
- Add overlay to the home page when a card's button is pressed
- Implement display mechanism of "View and Edit" form

Home page Implementation P2

---

Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceiptCard.jsx
Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceitCard.css

- Complete NewReceiptCard component UI implementation
- Add a mechanism to add and remove products from the table and remove items that are below 0 count

Table's logic implementation

---

Receiptly/receiptly-front/src/Api/api.js
Receiptly/receiptly-front/src/Components/Navbar/Navbar.css
Receiptly/receiptly-front/src/Components/Navbar/Navbar.jsx
Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceiptCard.jsx
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.jsx
Receiptly/receiptly-front/src/Pages/Home.jsx

- Add Sign Up and Sign In buttons to the navbar
- Fetch information from the back-end side and display it on the home page dynamically
- Display info and fill inputs in NewReceiptCard component and implement dynamic change reflections

Back to Front connection

---

Receiptly/receiptly-front/src/Api/api.js
Receiptly/receiptly-front/src/Components/Navbar/Navbar.jsx
Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceiptCard.jsx
Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceitCard.css

- Add Edit and Save buttons to alter the form's information
- Add a read-only mechanism to prevent the user from altering the form without pressing the Edit button
- Add appropriate logic to gather the user's modifications and edit them by sending changed information to the back-end side

NewReceiptCard modifications

---

Receiptly/receiptly-front/src/App.css
Receiptly/receiptly-front/src/Components/ProductCard/ProductCard.css
Receiptly/receiptly-front/src/Components/ProductCard/ProductCard.jsx
Receiptly/receiptly-front/src/Pages/Products.jsx

- Add Navbar component to the Products page
- Create ProductCard component and add a few instances to the Products page
- Add corresponding styles to ProductCard component
- Add default values to the ProductCard component

Products page implementation

---

Receiptly/receiptly-front/package-lock.json
Receiptly/receiptly-front/package.json
Receiptly/receiptly-front/src/App.css
Receiptly/receiptly-front/src/App.js
Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceiptCard.jsx
Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceitCard.css
Receiptly/receiptly-front/src/Components/ProductCard/ProductCard.css
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.css
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.jsx
Receiptly/receiptly-front/src/GraphQL/Client.js
Receiptly/receiptly-front/src/Pages/Home.jsx

- Install GraphQL and react-icons dependencies
- Add icons to NewReceiptCard component for adding and removing products and closing the card
- Setup GraphQL client and provider for the project
- Modify styles of cards and the card container CSS classes on the home page

GraphQL and modification

---

Receiptly/api/schema.py
Receiptly/api/urls.py

- Receipts and products can be queried by ID as well as all at once
- graphiql changed to graphiq

Receipts and products in graphQL

---

Receiptly/Receiptly/settings.py
Receiptly/receiptly-front/src/App.css
Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceiptCard.jsx
Receiptly/receiptly-front/src/Components/ProductCard/ProductCard.jsx
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.jsx
Receiptly/receiptly-front/src/GraphQL/Client.js
Receiptly/receiptly-front/src/Pages/Home.jsx
Receiptly/receiptly-front/src/Pages/Products.jsx

- Fetch and display the receipts via graphQl API call
- Fetch and display the products via GraphQL API call
- Add the filter option to the home page to filter receipts according to their states

API handling with GraphQL and the filter feature

---

Receiptly/receiptly-front/src/App.css
Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceiptCard.jsx
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.css
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.jsx
Receiptly/receiptly-front/src/Pages/Home.jsx

- Add a colored section above Receipt cards to indicate the state of the receipt
- Change the query for obtaining receipts from the back-end side
- Alter the filtering mechanism on the home page to filter the receipts based on their state

ReceiptCards styles modifications

---

Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceiptCard.jsx
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.css
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.jsx
Receiptly/receiptly-front/src/Pages/Home.jsx
Receiptly/receiptly-front/src/Pages/Products.jsx

- Add a mechanism to display a danger icon if we are within the deadlinenotic date.
- Fix bugs regarding total count and total efforts in the NewReceiptCard component
- Fix the problem regarding representing the products with GOOD labels on the Your Products page

Bug and alterations in the home and products pages

---

Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceiptCard.jsx
Receiptly/receiptly-front/src/GraphQL/Mutations.js
Receiptly/receiptly-front/src/Pages/Home.jsx

- Fix issues regarding data not being displayed on the form.
- Create Mutations.js file to add mutations to this file.
- Create a mutation to edit a receipt.
- The form within NewReceiptCard component now successfully edits the receipt's info.

Fix bugs and make NewReceiptCard dynamic

---

Receiptly/receiptly-front/package-lock.json
Receiptly/receiptly-front/package.json
Receiptly/receiptly-front/src/Components/Form/Form.jsx
Receiptly/receiptly-front/src/Components/Form/Form.module.css
Receiptly/receiptly-front/src/Components/Form/FormStepOne/FormStepOne.jsx
Receiptly/receiptly-front/src/Components/Form/FormStepThree/FormStepThree.jsx
Receiptly/receiptly-front/src/Components/Form/FormStepTwo/FormStepTwo.jsx
Receiptly/receiptly-front/src/Pages/Home.jsx

- Create a new component called Form
- Create three individual step components, each for one.
- Implement the logic of navigating between steps in Form component

Make a multi-step form

---

Receiptly/receiptly-front/src/Components/Form/Form.jsx
Receiptly/receiptly-front/src/Components/Form/Form.module.css
Receiptly/receiptly-front/src/Components/Form/FormStepOne/FormStepOne.jsx
Receiptly/receiptly-front/src/Components/Form/FormStepOne/FormStepOne.module.css
Receiptly/receiptly-front/src/Components/NewReceiptCard/NewReceitCard.css
Receiptly/receiptly-front/src/context/FormContext.js

- Implement the layout of the StepOne component.
- Create a Context for managing data among steps.
- Implement a mechanism to reserve the updated fields when navigating back to step one.

Completion of the step one of the form

---

Receiptly/receiptly-front/src/Components/Form/Form.jsx
Receiptly/receiptly-front/src/Components/Form/FormStepTwo/FormStepTwo.jsx
Receiptly/receiptly-front/src/Components/Form/FormStepTwo/FormStepTwo.module.css

- Create a two-sided form to display available products and the products within a receipt.
- Display products within a receipt successfully in a table
- Mock displaying available products in a second table
- Create a button to add available products to the list of products within the receipt.

FormStepTwo implementation

---

Receiptly/receiptly-front/src/Components/ProductCard/ProductCard.jsx
Receiptly/receiptly-front/src/Components/ProductForm/ProductForm.jsx
Receiptly/receiptly-front/src/Components/ProductForm/ProductForm.module.css
Receiptly/receiptly-front/src/GraphQL/Product.js

- Create a modal form for creating a new product.
- Create a mutation to deliver data to the back-end side.
- Complete the implementation of ProductForm component.

New Product implementation

---

Receiptly/receiptly-front/src/Components/ProductCard/ProductCard.jsx
Receiptly/receiptly-front/src/Components/ProductForm/ProductForm.jsx
Receiptly/receiptly-front/src/GraphQL/Product.js
Receiptly/receiptly-front/src/Pages/Products.jsx

- Implement an editing mechanism for products.
- Implement a deleting mechanism for products.

Edit & delete products

---

Receiptly/receiptly-front/src/Components/Filter/Filter.jsx
Receiptly/receiptly-front/src/GraphQL/Product.js
Receiptly/receiptly-front/src/GraphQL/Receipt.js
Receiptly/receiptly-front/src/Pages/Home.jsx
Receiptly/receiptly-front/src/Pages/Products.jsx

- Refactor Home and Product page codes.
- Add a filter option to the Product page.
- Create a Filter component, and deliver the duplicated logic to it.

Filter component and refactoring

---

Receiptly/receiptly-front/src/App.css
Receiptly/receiptly-front/src/Components/Form/Form.jsx
Receiptly/receiptly-front/src/Components/Form/FormStepOne/FormStepOne.jsx
Receiptly/receiptly-front/src/Components/Form/FormStepThree/FormStepThree.jsx
Receiptly/receiptly-front/src/Components/Form/FormStepTwo/FormStepTwo.jsx
Receiptly/receiptly-front/src/Components/Navbar/Navbar.jsx
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.css
Receiptly/receiptly-front/src/GraphQL/Receipt.js
Receiptly/receiptly-front/src/context/FormContext.js

- Fix bugs regarding displaying the modal card ( Form component ).
- Modify the Form component and its sub-components to handle both add and edit receipt processes.
- Add the newReceipt mutation.
- Add functionality to the "New Receipt " button in the Navbar component.

Fixing visual bugs and implement add receipt

---

Receiptly/receiptly-front/src/Components/Form/FormStepThree/FormStepThree.jsx
Receiptly/receiptly-front/src/Components/Form/FormStepTwo/FormStepTwo.jsx

- Add proper error-handling logic to the FormStepThree component.
- Fix the issue regarding multiple add and delete operations within the FormStepTwo component

Fix Form component bugs and add error handling

---

Receiptly/receiptly-front/src/App.css
Receiptly/receiptly-front/src/Components/Navbar/Navbar.css
Receiptly/receiptly-front/src/Components/Navbar/Navbar.jsx
Receiptly/receiptly-front/src/Components/ReceiptCard/ReceiptCard.css

- Add functionality that handles responsive behavior on the home page.

Make the home page responsive

---

Receiptly/receiptly-front/src/Components/Navbar/Navbar.jsx
Receiptly/receiptly-front/src/Components/Sign/SignIn/SignIn.jsx
Receiptly/receiptly-front/src/GraphQL/Auth.js

- Create mutations for the Login and Register processes.
- Implement the token-acquiring process through the Sign-in process. ( From the back-end side )
- Implement a mechanism to hide Sign-in/Sign-up buttons when the user is logged in.

Sign In process implementation

---

Receiptly/receiptly-front/package-lock.json
Receiptly/receiptly-front/package.json
Receiptly/receiptly-front/src/Components/Button/Button.jsx
Receiptly/receiptly-front/src/Components/Form/FormStepTwo/FormStepTwo.jsx
Receiptly/receiptly-front/src/Components/Navbar/Navbar.jsx
Receiptly/receiptly-front/src/Components/Sign/SignIn/SignIn.jsx
Receiptly/receiptly-front/src/Components/Sign/SignUp/SignUp.jsx
Receiptly/receiptly-front/src/Components/TextInput/TextInput.jsx
Receiptly/receiptly-front/src/Pages/Home.jsx

- Install Yup, @hookform/resolvers, and react-hook-form to handle forms.
- Add form validation mechanism to the Sign-In page.

Add input validation to the Sign In page

---

Receiptly/receiptly-front/package-lock.json
Receiptly/receiptly-front/package.json
Receiptly/receiptly-front/src/App.test.js
Receiptly/receiptly-front/src/Components/Sign/SignIn/SignIn.jsx
Receiptly/receiptly-front/src/Components/Sign/SignIn/SignIn.test.jsx

- Install RTL and Jest.
- Test all elements exist on the Sign-in page, and throw errors when input fields are empty.

Test input validation in the SignIn component

---

Receiptly/receiptly-front/src/Components/Sign/SignIn/SignIn.test.jsx

- Create test cases for checking input validation and authentication processes.

Finish testing the Sign-in component

---

Receiptly/receiptly-front/src/Components/Pagination/Pagination.jsx
Receiptly/receiptly-front/src/Components/Pagination/Pagination.module.css
Receiptly/receiptly-front/src/Pages/Home.jsx

- Create the Pagination.tsx component.
- Implement the logic of the Pagination component.
- Style the component.

Create and implement the pagination component

---

Receiptly/receiptly-front/src/Components/Pagination/Pagination.jsx
Receiptly/receiptly-front/src/Components/Pagination/Pagination.module.css
Receiptly/receiptly-front/src/Components/Pagination/Pagination.test.jsx
Receiptly/receiptly-front/src/Pages/Home.jsx

- Add 8 test cases to the Pagination. test.jsx file.
- Test existence in the document, changing activePage state correctness, and being disabled if we are already on the last or first page ( for next and prev buttons )

(test): complete testing of the Pagination component
